"""Renamend the ml data models

Revision ID: 9ab3a861d10c
Revises: c3b9d9d36877
Create Date: 2022-01-10 09:55:20.766392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab3a861d10c'
down_revision = 'c3b9d9d36877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
