# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Machine Learning Serving API
author: Eligijus Bujokas 

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib
  
sphinx:
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite

# Information about where the book exists on the web
repository:
  url: https://github.com/Eligijus112/api-book # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
