version: '3.1'

services:

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user 
    ports:
      - "5439:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data