jwt: 
  secret: 2134szczxc578214zxc~!?sad2
  algorithm: HS256
  expiration_time: 60

secrets: 
  key: tsdNFxCWtMNx48Z33oj_Q1cSsVmgQofqIB2gCrzur10=
  salt: 478213xzc345!

connection: 
  username: user
  password: password
  port: 5432
  database: postgres
  host: psql_db