version: '3.1'

services:

  psql_db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user 
    ports:
      - "5444:5432"
    volumes:
      - ./data_docker/db:/var/lib/postgresql/data

  ml_api:
    image: ml-api
    restart: always
    ports:
      - "8999:8900"
    